version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - goconst
    - gocritic
    - godot
    - gosec
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      match-constant: false
      ignore-tests: true
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: true
    staticcheck:
      checks:
        - all
        - ST1*
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
