/*
Copyright © 2024 Aristides Gonzalez <aristides@glezpol.com>
*/

package cmd

import (
	"bytes"
	encodingjson "encoding/json"
	"fmt"
	stdhtml "html"
	"strings"
)

func renderOrganizationTreeHTML(root organizationNode) []byte {
	var output strings.Builder
	policies := make(map[string]organizationPolicy, len(root.Policies))
	for _, policy := range root.Policies {
		policies[policy.ID] = policy
	}

	title := "AWS organization"
	if root.Selection.Type == allSelectionType {
		title = "Full AWS organization"
	} else if target := findOrganizationNode(root, root.Selection.TargetID); target != nil {
		title = organizationTextLabel(*target)
	}

	output.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n")
	output.WriteString("<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&output, "<title>Policy Scout — %s</title>\n", escapeHTML(title))
	output.WriteString(`<style>
:root { color-scheme: light dark; font-family: system-ui, sans-serif; }
body { margin: 0 auto; max-width: 80rem; padding: 2rem; background: Canvas; color: CanvasText; }
h1 { margin-bottom: .25rem; } .subtitle { color: GrayText; margin-top: 0; }
details { border: 1px solid color-mix(in srgb, CanvasText 18%, transparent); border-radius: .5rem; margin: .65rem 0; background: color-mix(in srgb, Canvas 94%, CanvasText 6%); }
details details { margin-left: 1rem; margin-right: .65rem; }
summary { cursor: pointer; font-weight: 650; line-height: 1.4; overflow-wrap: anywhere; padding: .8rem 1rem; }
.body { border-top: 1px solid color-mix(in srgb, CanvasText 14%, transparent); padding: .8rem 1rem 1rem; }
.badge { display: inline-block; border-radius: 999px; font-size: .72rem; letter-spacing: .04em; margin-right: .5rem; padding: .18rem .48rem; text-transform: uppercase; background: #2563eb; color: white; }
.scp > summary .badge { background: #7c3aed; } .management { background: #b45309; }
dl { display: grid; grid-template-columns: max-content minmax(0, 1fr); gap: .35rem 1rem; margin: 0 0 1rem; }
dt { color: GrayText; } dd { margin: 0; overflow-wrap: anywhere; }
.empty { color: GrayText; font-style: italic; } pre { overflow: auto; padding: 1rem; border-radius: .4rem; background: #111827; color: #e5e7eb; }
code { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }
@media (max-width: 40rem) {
  body { padding: .75rem; }
  details details { margin-left: .35rem; margin-right: 0; }
  summary { padding: .75rem; }
  .body { padding: .65rem; }
  dl { display: block; }
  dt { font-size: .8rem; }
  dd { margin-bottom: .65rem; }
  pre { font-size: .78rem; overflow-wrap: anywhere; padding: .65rem; white-space: pre-wrap; }
}
</style>
</head>
<body>
`)
	fmt.Fprintf(&output, "<h1>%s</h1>\n", escapeHTML(title))
	fmt.Fprintf(&output, "<p class=\"subtitle\">Generated by Policy Scout · selection: %s</p>\n", escapeHTML(root.Selection.Type))
	renderOrganizationHTMLNode(&output, root, policies, root.Selection, true)
	output.WriteString("</body>\n</html>\n")
	return []byte(output.String())
}

func renderOrganizationHTMLNode(
	output *strings.Builder,
	node organizationNode,
	policies map[string]organizationPolicy,
	selection organizationSelection,
	open bool,
) {
	openAttribute := ""
	if open {
		openAttribute = " open"
	}
	fmt.Fprintf(output, "<details class=\"entity %s\"%s>\n", escapeHTML(node.Type), openAttribute)
	badge := organizationHTMLTypeLabel(node.Type)
	fmt.Fprintf(output, "<summary><span class=\"badge\">%s</span>%s", escapeHTML(badge), escapeHTML(node.Name))
	if node.Name != "" {
		output.WriteString(" ")
	}
	fmt.Fprintf(output, "<code>[%s]</code>", escapeHTML(node.ID))
	if node.ManagementAccount {
		output.WriteString(" <span class=\"badge management\">management</span>")
	}
	output.WriteString("</summary>\n<div class=\"body\">\n<dl>")
	renderHTMLAttribute(output, "Type", node.Type)
	renderHTMLAttribute(output, "ID", node.ID)
	if node.Name != "" {
		renderHTMLAttribute(output, "Name", node.Name)
	}
	switch node.Type {
	case rootEntityType:
		renderHTMLAttribute(output, "Schema version", node.SchemaVersion)
		renderHTMLAttribute(output, "Selection", node.Selection.Type)
		if node.Selection.TargetID != "" {
			renderHTMLAttribute(output, "Target ID", node.Selection.TargetID)
		}
	case accountEntityType:
		renderHTMLAttribute(output, "Management account", fmt.Sprint(node.ManagementAccount))
	}
	output.WriteString("</dl>\n")

	if node.Type == accountEntityType || node.Type == organizationalUnitEntityType {
		output.WriteString("<h3>Service control policies</h3>\n")
		switch {
		case node.ManagementAccount:
			output.WriteString("<p class=\"empty\">SCPs do not affect this account’s users or roles.</p>\n")
		case len(node.SCPAttachments) == 0 && len(node.SCPs) == 0:
			output.WriteString("<p class=\"empty\">No applicable SCP attachments.</p>\n")
		case len(node.SCPAttachments) == 0:
			fmt.Fprintf(output, "<p>Applicable SCPs: %s</p>\n", escapeHTML(strings.Join(node.SCPs, ", ")))
		default:
			for _, attachment := range node.SCPAttachments {
				renderOrganizationHTMLAttachment(output, attachment, policies)
			}
		}
	}

	if len(node.Children) > 0 {
		output.WriteString("<h3>Children</h3>\n")
		for _, child := range node.Children {
			renderOrganizationHTMLNode(output, child, policies, selection, false)
		}
	} else if node.Type == organizationalUnitEntityType && node.ID == selection.TargetID {
		output.WriteString("<h3>Children</h3>\n<p class=\"empty\">Descendants were not requested for this selected OU.</p>\n")
	}
	output.WriteString("</div>\n</details>\n")
}

func renderOrganizationHTMLAttachment(
	output *strings.Builder,
	attachment scpAttachment,
	policies map[string]organizationPolicy,
) {
	status := "direct"
	summaryStatus := status
	if attachment.Inherited {
		status = "inherited"
		summaryStatus = status + " from " + attachmentTargetText(attachment.AttachedTo)
	}
	fmt.Fprintf(
		output,
		"<details class=\"scp\"><summary><span class=\"badge\">SCP</span>%s <code>[%s]</code> — %s</summary>\n<div class=\"body\"><dl>",
		escapeHTML(attachment.PolicyName),
		escapeHTML(attachment.PolicyID),
		escapeHTML(summaryStatus),
	)
	renderHTMLAttribute(output, "Policy ID", attachment.PolicyID)
	renderHTMLAttribute(output, "Policy name", attachment.PolicyName)
	renderHTMLAttribute(output, "Attachment", status)
	renderHTMLAttribute(output, "Attached to type", attachment.AttachedTo.Type)
	renderHTMLAttribute(output, "Attached to ID", attachment.AttachedTo.ID)
	if attachment.AttachedTo.Name != "" {
		renderHTMLAttribute(output, "Attached to name", attachment.AttachedTo.Name)
	}
	output.WriteString("</dl>\n")

	if policy, ok := policies[attachment.PolicyID]; ok {
		output.WriteString("<h4>Policy details</h4><dl>")
		if policy.Description != "" {
			renderHTMLAttribute(output, "Description", policy.Description)
		}
		if policy.ARN != "" {
			renderHTMLAttribute(output, "ARN", policy.ARN)
		}
		renderHTMLAttribute(output, "AWS managed", fmt.Sprint(policy.AWSManaged))
		output.WriteString("</dl><h4>Policy document</h4><pre><code>")
		output.WriteString(escapeHTML(formatPolicyDocument(policy.Content)))
		output.WriteString("</code></pre>\n")
	}
	output.WriteString("</div></details>\n")
}

func renderHTMLAttribute(output *strings.Builder, name, value string) {
	fmt.Fprintf(output, "<dt>%s</dt><dd>%s</dd>", escapeHTML(name), escapeHTML(value))
}

func organizationHTMLTypeLabel(entityType string) string {
	switch entityType {
	case rootEntityType:
		return rootEntityLabel
	case organizationalUnitEntityType:
		return organizationalUnitEntityLabel
	case accountEntityType:
		return accountEntityLabel
	default:
		return "Entity"
	}
}

func formatPolicyDocument(content encodingjson.RawMessage) string {
	var formatted bytes.Buffer
	if err := encodingjson.Indent(&formatted, content, "", "  "); err != nil {
		return string(content)
	}
	return formatted.String()
}

func escapeHTML(value string) string {
	return stdhtml.EscapeString(value)
}
